[build]
  base = "./"
  command = "gatsby build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  package = "netlify-plugin-amp-server-side-rendering"
  package = "@netlify/plugin-lighthouse"